"""initial without users table

Revision ID: 373ca7396fa1
Revises: 
Create Date: 2026-05-15 22:20:49.113279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '373ca7396fa1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('subtitle', sa.String(length=256), nullable=True),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('slurry_type', sa.String(length=64), nullable=True),
    sa.Column('crop', sa.String(length=128), nullable=True),
    sa.Column('soil_type', sa.String(length=128), nullable=True),
    sa.Column('dosage', sa.String(length=128), nullable=True),
    sa.Column('application_method', sa.String(length=128), nullable=True),
    sa.Column('yield_benefit', sa.Text(), nullable=True),
    sa.Column('quality_benefit', sa.Text(), nullable=True),
    sa.Column('risk_control', sa.Text(), nullable=True),
    sa.Column('understanding_points', sqlite.JSON(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('source_citation', sa.Text(), nullable=True),
    sa.Column('authors', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_index('ix_articles_status', 'articles', ['status'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('authors', sa.String(length=512), nullable=True),
    sa.Column('journal', sa.String(length=256), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('parsed_path', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('article_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_papers_status', 'papers', ['status'], unique=False)
    op.create_table('qa_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qa_messages_article_id', 'qa_messages', ['article_id'], unique=False)
    op.create_index('ix_qa_messages_session_id', 'qa_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qa_messages_session_id', table_name='qa_messages')
    op.drop_index('ix_qa_messages_article_id', table_name='qa_messages')
    op.drop_table('qa_messages')
    op.drop_index('ix_papers_status', table_name='papers')
    op.drop_table('papers')
    op.drop_index('ix_articles_status', table_name='articles')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
